######################################################################
# Automatically generated by qmake (3.0) ?? 6? 7 17:41:09 2016
######################################################################

TEMPLATE = app
TARGET = xcar

# install
target.path = /home/pi
INSTALLS += target


INCLUDEPATH += .

QT += widgets

LIBS += -lvlc -lwiringPi  -lwiringPiDev

# Input
HEADERS += \
    Xcar.h \
    CtrlComm.h
 #   SerialThread.h


SOURCES += main.cpp \
    Xcar.cpp
  #  Serialthread.cpp



